CONNECT oracle/dummypassword@localhost:1521/XEPDB1

ALTER SESSION SET CURRENT_SCHEMA = MOVIE_STREAM_DB;

-- Create users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) NOT NULL UNIQUE,
    email VARCHAR2(255) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    subscriptionId NUMBER
);

-- Create subscriptions table
CREATE TABLE subscriptions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId NUMBER,
    packageName VARCHAR2(255) NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id)
);

-- Create payments table
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId NUMBER,
    subscriptionId NUMBER,
    transactionDate TIMESTAMP NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id)
);

-- Insert data into users table
INSERT INTO users (username, password, subscriptionId) VALUES ('user1', 'password1', 'abc@dummymail.com', 1);
INSERT INTO users (username, password, subscriptionId) VALUES ('user2', 'password2', 'def@dummymail.com', 2);
INSERT INTO users (username, password, subscriptionId) VALUES ('user3', 'password3', 'ghi@dummymail.com', 3);

-- Insert data into subscriptions table
INSERT INTO subscriptions (userId, packageName, startDate, endDate, price) VALUES 
(1, 'BASIC', DATE '2024-01-01', DATE '2024-12-31', 3.99);
INSERT INTO subscriptions (userId, packageName, startDate, endDate, price) VALUES 
(2, 'PREMIUM', DATE '2024-01-01', DATE '2024-12-31', 3.99);
INSERT INTO subscriptions (userId, packageName, startDate, endDate, price) VALUES 
(3, 'PREMIUM', DATE '2024-01-01', DATE '2024-12-31', 44.99);


-- Insert data into payments table
INSERT INTO payments (userId, subscriptionId, transactionDate, amount) VALUES 
(1, 1, TIMESTAMP '2024-07-04 00:00:00', 3.99);
INSERT INTO payments (userId, subscriptionId, transactionDate, amount) VALUES 
(2, 2, TIMESTAMP '2024-07-04 00:00:00', 3.99);
INSERT INTO payments (userId, subscriptionId, transactionDate, amount) VALUES 
(3, 3, TIMESTAMP '2024-07-04 00:00:00', 44.99);

-- Add check constraint to payments table
ALTER TABLE payments
ADD CONSTRAINT chk_amount CHECK (amount >= 3.99);
